### ISSUE TITLE
影に入ると受けるダメージについて

### ISSUE THREAD

**Issue by Rasshiine** [Rasshine/Rasshine#3]
Sphereと接触していないときにダメージを与える方法がわからなかったので、256行目と361行目で回復とダメージで釣り合いを取ろうとしたのですが、値は同じはずなのにHPが変動してうまくいきません。何かこれを実装する良い方法はないでしょうか？

**Comment by fukuchang** [comment]
お疲れ様です！
今確認しました！遅くなって申し訳ない！
具体的にどこのスクリプトの256行目と361行目を指してますか？
教えてくれるとスムーズにスクリプトをみれるかも
（プロジェクトファイルの容量が大きすぎてpullに時間がかかってるーーーー。←頑張ってる証拠）
